apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server:7.6.0
    init: confluentinc/confluent-init-container:2.8.0
  dataVolumeCapacity: 20Gi
  storageClass:
    name: standard
  dependencies:
    kRaftController:
      clusterRef:
        name: kraft-controller
  podTemplate:
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
    probe:
      liveness:
        initialDelaySeconds: 60
        failureThreshold: 10
      readiness:
        initialDelaySeconds: 60
        failureThreshold: 10
  configOverrides:
    server:
      - default.replication.factor=1
      - min.insync.replicas=1
      - auto.create.topics.enable=false
  listeners:
    internal:
      tls:
        enabled: false